# Generated by Django 6.0.1 on 2026-02-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_reporter_email_remove_reporter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='reporter',
            field=models.TextField(),
        ),
    ]
