# Generated by Django 6.0.1 on 2026-04-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_articles_category_alter_articles_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='featured_Image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
