# Generated by Django 6.0.1 on 2026-04-22 02:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_articles_featured_image_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
        migrations.AddField(
            model_name='categories',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
