# Generated by Django 6.0.1 on 2026-01-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_Picture', models.ImageField(null=True, upload_to='profile_pic')),
            ],
        ),
    ]
